apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: web-server
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-volume
    resources:
      limits:
        cpu: "1.0"
        memory: "128Mi"
      requests:
        cpu: "0.5"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: 256Mi