apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["sleep", "2400"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
