apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    #command: ["sleep", "2400"]
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
    args:
    - sleep
    - "2400"  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
